zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - "2181:2181"
kafka:
  image: wurstmeister/kafka
  ports:
    - "9092:9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
    KAFKA_CREATE_TOPICS: "test:1:1"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
kafka-manager:
  image: sheepkiller/kafka-manager
  ports:
    - "29000:9000"
  links:
    - zookeeper:zk
  environment:
    ZK_HOSTS: zk:2181

nexus:
  build: ./nexus
  ports:
    - "18081:8081"

jenkins:
  build: ./jenkins
  ports:
    - "18080:8080"
  links:
    - nexus:nexus
    - sonar:sonar
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/bin/docker

registry:
  image: registry
  environment:
    - STORAGE_PATH=/registry
  volumes:
    - registry-stuff:/registry
  ports:
    - "5000:5000"

sonar:
  build: ./sonar
  ports:
   - "19000:9000"
   - "5432:5432"
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://localhost:5432/sonar
db:
  image: postgres
  net: container:sonar
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar
