version: '3.2'

networks:
    prodnetwork:
        driver: bridge

volumes:
    nexus-data: {}
    registry-stuff:
        #Which driver to store 
        driver: local

services:
    registry:
        image: registry:2
        environment:
            - STORAGE_PATH=/var/lib/registry
#        volumes:
#            - registry-stuff:/registry
        ports:
            - "5000:5000"

    nexus:
        image: sonatype/nexus3
        ports:
            - "8081:8081"
        environment:
            - INSTALL4J_ADD_VM_PARAMS=-Xms500m -Xmx500m
        volumes:
            - "nexus-data:/nexus-data"
    jenkins:
        image: easyms-jenkins
        ports:
          - "8080:8080"
        links:
          - nexus:nexus
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /usr/local/bin/docker:/usr/bin/docker
        #environment:
        #  EDMP_CONFIG_URL: "https://raw.githubusercontent.com/codecentric/event-driven-microservices-platform-config/master/edmp-project-configuration.json"


