version: '2'

networks:
  prodnetwork:
    driver: bridge

volumes:
  registry-stuff:
    driver: local

services:
  edmp-monitoring:
    build: ./edmp-monitoring
    ports:
      - "10001:8080"
    networks:
      - prodnetwork
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - prodnetwork
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper:zk
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_CREATE_TOPICS: "test:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - prodnetwork
  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - "29000:9000"
    links:
      - zookeeper:zk
    environment:
      ZK_HOSTS: zk:2181
    networks:
      - prodnetwork

  nexus:
    build: ./nexus
    ports:
      - "18081:8081"

  jenkins:
    build: ./jenkins
    ports:
      - "18080:8080"
    links:
      - nexus:nexus
      - sonar:sonar
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker

  registry:
    image: registry
    environment:
      - STORAGE_PATH=/registry
    volumes:
      - registry-stuff:/registry
    ports:
      - "5000:5000"

  sonar:
    build: ./sonar
    ports:
     - "19000:9000"
    environment:
     - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
  sonardb:
    image: postgres
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_USER=sonar
     - POSTGRES_PASSWORD=sonar
